### ISSUE TITLE
3D Camera

### ISSUE THREAD

**Issue by elpasto** [Fahien/spacefloat#1]
Check cameraFar parameter (does not work).
Check if it possible to use an OrthographicCamera also for 3D

far (public float far)
the far clipping plane distance, has to be positive => This change clipping plane, not camera zoom

**Comment by Fahien** [comment]
With 7e950ca9862892d92dca30dc2d7bf5fd058136e1 you have can configure the type and the zoom of the main camera via the Space Float configuration file:

* **cameraType**:
 * perspective (for the Perspective Camera);
 * orthographic (for the Orthographic Camera).
* **cameraZoom**: [1.0, 8.0] (must be comprised between 1.0 and 8.0)
